export const SquaresFactoryABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_functionsRouter', type: 'address' },
      { name: '_vrfCoordinator', type: 'address' },
      { name: '_automationRegistrar', type: 'address' },
      { name: '_functionsSubscriptionId', type: 'uint64' },
      { name: '_functionsDonId', type: 'bytes32' },
      { name: '_vrfSubscriptionId', type: 'uint256' },
      { name: '_vrfKeyHash', type: 'bytes32' },
      { name: '_creationFee', type: 'uint256' },
    ],
  },
  {
    type: 'function',
    name: 'createPool',
    inputs: [
      {
        name: 'params',
        type: 'tuple',
        components: [
          { name: 'name', type: 'string' },
          { name: 'squarePrice', type: 'uint256' },
          { name: 'paymentToken', type: 'address' },
          { name: 'maxSquaresPerUser', type: 'uint8' },
          { name: 'payoutPercentages', type: 'uint8[4]' },
          { name: 'teamAName', type: 'string' },
          { name: 'teamBName', type: 'string' },
          { name: 'purchaseDeadline', type: 'uint256' },
          { name: 'vrfTriggerTime', type: 'uint256' },
          { name: 'passwordHash', type: 'bytes32' },
        ],
      },
    ],
    outputs: [{ name: 'pool', type: 'address' }],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'getPoolsByCreator',
    inputs: [{ name: 'creator', type: 'address' }],
    outputs: [{ type: 'address[]' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getAllPools',
    inputs: [
      { name: 'offset', type: 'uint256' },
      { name: 'limit', type: 'uint256' },
    ],
    outputs: [
      { name: 'pools', type: 'address[]' },
      { name: 'total', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolCount',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolCountByCreator',
    inputs: [{ name: 'creator', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getPoolUpkeepId',
    inputs: [{ name: 'pool', type: 'address' }],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'functionsRouter',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'vrfCoordinator',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'automationRegistrar',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'creationFee',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultFunctionsSubscriptionId',
    inputs: [],
    outputs: [{ type: 'uint64' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultFunctionsDonId',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultFunctionsSource',
    inputs: [],
    outputs: [{ type: 'string' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultVRFSubscriptionId',
    inputs: [],
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'defaultVRFKeyHash',
    inputs: [],
    outputs: [{ type: 'bytes32' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'admin',
    inputs: [],
    outputs: [{ type: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'setDefaultFunctionsSource',
    inputs: [{ name: 'source', type: 'string' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFunctionsSubscription',
    inputs: [{ name: 'subscriptionId', type: 'uint64' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setFunctionsDonId',
    inputs: [{ name: 'donId', type: 'bytes32' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setCreationFee',
    inputs: [{ name: '_creationFee', type: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawFees',
    inputs: [{ name: 'to', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferAdmin',
    inputs: [{ name: 'newAdmin', type: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'PoolCreated',
    inputs: [
      { name: 'pool', type: 'address', indexed: true },
      { name: 'creator', type: 'address', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'squarePrice', type: 'uint256', indexed: false },
      { name: 'paymentToken', type: 'address', indexed: false },
      { name: 'upkeepId', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'CreationFeeUpdated',
    inputs: [
      { name: 'oldFee', type: 'uint256', indexed: false },
      { name: 'newFee', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'FeesWithdrawn',
    inputs: [
      { name: 'to', type: 'address', indexed: true },
      { name: 'amount', type: 'uint256', indexed: false },
    ],
  },
  {
    type: 'event',
    name: 'AdminTransferred',
    inputs: [
      { name: 'oldAdmin', type: 'address', indexed: true },
      { name: 'newAdmin', type: 'address', indexed: true },
    ],
  },
  {
    type: 'error',
    name: 'OnlyAdmin',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InsufficientCreationFee',
    inputs: [
      { name: 'sent', type: 'uint256' },
      { name: 'required', type: 'uint256' },
    ],
  },
  {
    type: 'error',
    name: 'TransferFailed',
    inputs: [],
  },
  {
    type: 'error',
    name: 'InvalidAddress',
    inputs: [],
  },
] as const;
